# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4aef09076887b7947770a7a53cf5252ddedc12d39b48e2a0d231ec86e7283f7dd37d36720900d1cd70ba699cb7aed980e3bc1309b7a700212448b75552103d99

test:
  secret_key_base: da7f024d71a8ab9063c77bba55af698b9d5a7d912219fd0600a68f9964d8b24aa0207b670280709437d1f036d53a4215559fe2272b92f5e65e5353b998694e4e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
